/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvBar as QvBarElement } from '@quevy/components';

export const QvBar = createComponent({
    tagName: 'qv-bar',
    elementClass: QvBarElement,
    react: React,
    displayName: 'QvBar',
});
