/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvBottomSheetInline as QvBottomSheetInlineElement } from '@quevy/components';

export const QvBottomSheetInline = createComponent({
    tagName: 'qv-bottom-sheet-inline',
    elementClass: QvBottomSheetInlineElement,
    react: React,
    displayName: 'QvBottomSheetInline',
});
