/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvBottomSheet as QvBottomSheetElement } from '@quevy/components';

export const QvBottomSheet = createComponent({
    tagName: 'qv-bottom-sheet',
    elementClass: QvBottomSheetElement,
    react: React,
    displayName: 'QvBottomSheet',
});
