/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvButton as QvButtonElement } from '@quevy/components';

export const QvButton = createComponent({
    tagName: 'qv-button',
    elementClass: QvButtonElement,
    react: React,
    displayName: 'QvButton',
});
