/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvCarousel as QvCarouselElement } from '@quevy/components';

export const QvCarousel = createComponent({
    tagName: 'qv-carousel',
    elementClass: QvCarouselElement,
    react: React,
    displayName: 'QvCarousel',
});
