/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvCalendar as QvCalendarElement } from '@quevy/components';

export const QvCalendar = createComponent({
    tagName: 'qv-calendar',
    elementClass: QvCalendarElement,
    react: React,
    displayName: 'QvCalendar',
});
