/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvDatepicker as QvDatepickerElement } from '@quevy/components';

export const QvDatepicker = createComponent({
    tagName: 'qv-datepicker',
    elementClass: QvDatepickerElement,
    react: React,
    displayName: 'QvDatepicker',
});
