/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvListItem as QvListItemElement } from '@quevy/components';

export const QvListItem = createComponent({
    tagName: 'qv-list-item',
    elementClass: QvListItemElement,
    react: React,
    displayName: 'QvListItem',
});
