/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvMenu as QvMenuElement } from '@quevy/components';

export const QvMenu = createComponent({
    tagName: 'qv-menu',
    elementClass: QvMenuElement,
    react: React,
    displayName: 'QvMenu',
});
