/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvModal as QvModalElement } from '@quevy/components';

export const QvModal = createComponent({
    tagName: 'qv-modal',
    elementClass: QvModalElement,
    react: React,
    displayName: 'QvModal',
});
