/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvNavbarItem as QvNavbarItemElement } from '@quevy/components';

export const QvNavbarItem = createComponent({
    tagName: 'qv-navbar-item',
    elementClass: QvNavbarItemElement,
    react: React,
    displayName: 'QvNavbarItem',
});
