/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvPopover as QvPopoverElement } from '@quevy/components';

export const QvPopover = createComponent({
    tagName: 'qv-popover',
    elementClass: QvPopoverElement,
    react: React,
    events: {
        onOpen: 'open',
        onClose: 'close',
    },
    displayName: 'QvPopover',
});
