/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvRadioGroup as QvRadioGroupElement } from '@quevy/components';

export const QvRadioGroup = createComponent({
    tagName: 'qv-radio-group',
    elementClass: QvRadioGroupElement,
    react: React,
    events: {
        onChange: 'change',
    },
    displayName: 'QvRadioGroup',
});
