/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvSideSheetInline as QvSideSheetInlineElement } from '@quevy/components';

export const QvSideSheetInline = createComponent({
    tagName: 'qv-side-sheet-inline',
    elementClass: QvSideSheetInlineElement,
    react: React,
    displayName: 'QvSideSheetInline',
});
