/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvSideSheet as QvSideSheetElement } from '@quevy/components';

export const QvSideSheet = createComponent({
    tagName: 'qv-side-sheet',
    elementClass: QvSideSheetElement,
    react: React,
    events: {
        onOpen: 'open',
        onClose: 'close',
    },
    displayName: 'QvSideSheet',
});
