/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvTable as QvTableElement } from '@quevy/components';

export const QvTable = createComponent({
    tagName: 'qv-table',
    elementClass: QvTableElement,
    react: React,
    displayName: 'QvTable',
});
