/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvTooltip as QvTooltipElement } from '@quevy/components';

export const QvTooltip = createComponent({
    tagName: 'qv-tooltip',
    elementClass: QvTooltipElement,
    react: React,
    displayName: 'QvTooltip',
});
