/**
 * AUTO-GENERATED by packages/react/scripts/generate-wrappers.mjs
 *
 * Do not edit this file by hand.
 * Re-run the generator instead.
 *
 * Source of truth:
 *   @quevy/components
 */

import { createComponent } from '@lit/react';
import * as React from 'react';

import { QvToastRegion as QvToastRegionElement } from '@quevy/components';

export const QvToastRegion = createComponent({
    tagName: 'qv-toast-region',
    elementClass: QvToastRegionElement,
    react: React,
    displayName: 'QvToastRegion',
});
